### ISSUE TITLE
Feature-Request: Add `executeScript()`

### ISSUE THREAD

**Issue by hepiyellow** [wix-incubator/unidriver#33] opened 2019-02-19 15:19 UTC
Both protractor and puppeteer have some way to execute scripts in the browser.
I guess that shows, that it is useful for tests.

Apart from that, it would be useful as an `last-resort` solution in the "growing-phase" of Unidriver, to accommodate missing features.

At first stage, I suggest to have `executeScript` without any return value.
That could be useful for doing `focus`, `blur`, pressing keys, etc...

The return value is a bit more tricky. But possible, I think.

**Comment by GabiGrin** [comment] 2019-02-19 18:42
Hey,
The core idea of UniDriver is doing what users would do. Users don’t
execute scripts.
Pressing keys is done and will be released very soon.
Focus and Blur are not planned to enter the library by design.

UniDriver exposed a very convenient escape hatch for everything it doesn’t
do (.getNative())
I would love to point to some suggestions and patterns on how to tackle
this but I do not see executeScript part it’s API.

Appreciated the suggestion and would be happy yo suggest alternatives

**Closed** 2019-03-04 19:59 UTC
Labels: enhancement
